#! /bin/bash
# Octopus Linux tentacle script
# Version: 1.0.0
# ------------------------------------------------------------------------------
# Script for 
#	get: Get the value of an Octopus variable
#	set: Set the value of an Octopus output variable
#	create: Create a new Octopus artifact
PROGNAME=$(basename $0)
source $(dirname $0)/functions

case "$1" in
	get)
		# Ensure they have passed in the Octopus Variable to retrieve
		if [ -z "$2" ]
		then
		  error_exit $PROGNAME $LINENO "Usage: $PROGNAME get \"octopus-variable\"\nExample: $PROGNAME get \"Octopus.Release.Number\"" $E_NO_ARGS
		  exit $?
		fi
		RETURN_VALUE=$(get_octopusvariable "$2") || exit $?
		echo $RETURN_VALUE
		;;
	set)
		# Ensure they have passed in the Octopus Variable to set and it's value
		if [ -z $2 ] || [ -z $3 ]
		then
			error_exit $PROGNAME $LINENO "Usage: $PROGNAME set \"octopus-variable\" \"variable-value\"\nExample: $PROGNAME \"OctopusOriginalPackageDirectoryPath" "${Octopus_Action_Ssh_ApplicationsDirectoryPath:${#HOME}+1}\"" $E_NO_ARGS
			exit $?
		fi
		RETURN_VALUE=$(set_octopusvariable $2 $3) || exit $?
		echo $RETURN_VALUE
		;; 
	collect)
		# Ensure they have passed in the full path and original filename for the artifact
		if [ -z $2 ]
		then
			error_exit $PROGNAME $LINENO "Usage: $PROGNAME collect \"path\" \"originalfilename\"\nExample: $PROGNAME create \"~\.tentacle\logs\Deployment.log\" \"Deployment.log\"" $E_NO_ARGS
			exit $?
		fi
		RETURN_VALUE=$(new_octopusartifact $2 $3) || exit $?
		echo $RETURN_VALUE
		;;
	subst)
		RETURN_VALUE=$(substitute_octopusvariables "$@") || exit $?
		echo $RETURN_VALUE
		;;
	*)
		echo "Unrecognized command \"$1\""
		exit 1
	    ;;
esac