using Autofac;
using Octopus.Server.Extensibility.Extensions.Mappings;
using Sashimi.Server.Contracts.Accounts;

namespace Sashimi.AzureCloudService
{
    public class AzureCloudServiceModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            base.Load(builder);

            builder.RegisterType<AzureSubscription>().As<IServiceMessageHandler>().As<IAccountTypeProvider>().InstancePerLifetimeScope();
            builder.RegisterType<AzureSubscriptionMappings>().As<IContributeMappings>().InstancePerDependency();
            builder.RegisterType<AzureCertificateMayBeAutoGenerated>().As<AccountStoreContributor>().InstancePerLifetimeScope();
            builder.RegisterType<AzureCertificateRequiresPrivateKey>().As<AccountStoreContributor>().InstancePerLifetimeScope();
            builder.RegisterType<AzureCertificateThumbprintWillBeSet>().As<AccountStoreContributor>().InstancePerLifetimeScope();
            builder.RegisterType<CertificateEncoder>().SingleInstance();
            builder.RegisterType<CertificateGenerator>().SingleInstance();
        }
    }
}