using System;
using System.Collections;

namespace Calamari.Kubernetes
{
    public class ApiResourceIdentifier : IEquatable<ApiResourceIdentifier>
    {
        public ApiResourceIdentifier(string apiVersion, string kind)
        {
            ApiVersion = apiVersion;
            Kind = kind;
        }

        string ApiVersion { get; }
        string Kind { get; }

        public bool Equals(ApiResourceIdentifier other)
        {
            if (other is null)
                return false;
            if (ReferenceEquals(this, other))
                return true;
            return ApiVersion == other.ApiVersion
                   && Kind == other.Kind;
        }

        public override bool Equals(object obj)
        {
            if (obj is null)
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            if (obj.GetType() != GetType())
                return false;
            return Equals((ApiResourceIdentifier)obj);
        }

        public override int GetHashCode()
        {
            // Generated by Rider
            unchecked
            {
                return ((ApiVersion != null ? ApiVersion.GetHashCode() : 0) * 397) ^ (Kind != null ? Kind.GetHashCode() : 0);
            }
        }
    }
}