package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            param("teamcity.vcsTrigger.runBuildInNewEmptyBranch", "true")
        }
        add {
            param("FeedzIoApiKey", "credentialsJSON:4f54a8df-ea59-4d49-90df-39c9ad1afd05")
        }
    }
}
