---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: {}
status: {}
---
apiVersion: v1
data:
  A: a
  B: b
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curl
  name: curl
  namespace: default
spec:
  containers:
    - image: curl
      name: curl
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}