apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unexpected
  annotations:
    app: unexpected
  name: deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app: expected
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      containers:
        - name: pause
          image: pause
